# cloudbuild.yaml — fixed and validated
substitutions:
  _AR_HOSTNAME: 'europe-west1-docker.pkg.dev'
  _AR_PROJECT_ID: 'lofty-voyage-477911-m6'
  _AR_REPOSITORY: 'cloud-run-source-deploy'
  _DEPLOY_REGION: 'europe-west1'
  _PLATFORM: 'managed'
  _SERVICE_NAME: 'deploy'
  _TRIGGER_ID: '46310ca3-3f21-444c-b59b-403ff8109133'

steps:
  # Step 1 — Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    entrypoint: bash
    args:
      - -c
      - |
        IMAGE_URI="${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest"
        echo "Building ${IMAGE_URI}"
        docker build -t "${IMAGE_URI}" .

  # Step 2 — Push
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    entrypoint: bash
    args:
      - -c
      - |
        IMAGE_URI="${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest"
        echo "Pushing ${IMAGE_URI}"
        docker push "${IMAGE_URI}"

  # Step 3 — Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        IMAGE_URI="${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest"
        echo "Deploying ${_SERVICE_NAME} to ${_DEPLOY_REGION}"
        gcloud run deploy "${_SERVICE_NAME}" \
          --image "${IMAGE_URI}" \
          --region "${_DEPLOY_REGION}" \
          --platform "${_PLATFORM}" \
          --allow-unauthenticated \
          --memory 8Gi \
          --cpu 2 \
          --timeout 900

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
